### ISSUE TITLE
[Jobs] - Trucker Job

### ISSUE THREAD

**Issue by andreirosu97** [B-Zone-GTA-V/B-Zone-GTA-V-Tracker#103]
Implement the trucker job from the line of command.

Job steps:
- [ ] /getjob at a checkpoint to get the trucker job
- [ ] go to the checkpoint with NPC to rent job vehicle (will probably cost some cash) - `vehicle.SetData("JobType", "Trucker")`
- [ ] /startjob (will be replaced with Take Job from the mobile app) this will check if you are in a job-specific vehicle if need be
![Image](https://user-images.githubusercontent.com/26410774/180625819-9a80f9ff-d4a2-4889-935f-bfe0f85d6f66.png)
- [ ] /canceljob will stop the current job and you will get punishment and the job will be placed back in the job list

**Start job:** 
- Set the player the job ID
- The player can't take any other job if he already has one started
- If the player disconnects will automatically /canceljob

**The job:**
- Go to the set checkpoint based on the jobs description to pick up the trailer
- Go with the trailer at the set checkpoint on the map to drop it off
- Go back to the jobs start location to get the payout
- Then the job is finished and removed from the db

**The jobs:** 
- Create 3 routes and place them in the db
- Those are not removed when the player takes them if they are from 'B-Zone' containing string contractor

**Comment by robertnitu02** [comment]
outdated
Check doc
