### ISSUE TITLE
[Phone] - [Messages] - Save the last messages when the user disconnects from the game session

### ISSUE THREAD

**Issue by SaRtORx** [B-Zone-GTA-V/B-Zone-GTA-V-Tracker#365]
Save the last messages when the user disconnects from the game session

We can also try to discover if we can add the time when the message was received (eg: 12:34 PM).
If the message was received yesterday we should just display "yesterday" instead of the time of the message being received.

**Comment by robertnitu02** [comment]
https://github.com/B-Zone-GTA-V/B-Zone-GTA-V-Tracker/issues/465
