### ISSUE TITLE
[Animation System] - Implement Composed Animations

### ISSUE THREAD

**Issue by SaRtORx** [B-Zone-GTA-V/B-Zone-GTA-V-Tracker#379]
This task will be set to low priority as it will require two different users to interact with another user in order to trigger those animations.

We want to investigate whether it is relevant to add each animation as a command, for example for facial animations we can add commands such as /angry /nervous /scared.

Currently, it seems that these commands do not make sense to be translated into Romanian.

**Comment by andreirosuselfpay** [comment]
The flow should be the following:

**Transmit**
Player 1: K -> Animations -> Composed -> (Opens mouse select entity) DO CHECKS OF DISTANCE
Player 2: Receives persistent notification with the animation name

**Receive**
Player 2: K -> Animations -> Accept Animation (DO CHECKS OF DISTANCE)

This should have expiration similar to trade
This should be not priority animation, cancelable by any player
