### ISSUE TITLE
[Shops] - Tattoo shop

### ISSUE THREAD

**Issue by andreirosu97** [B-Zone-GTA-V/B-Zone-GTA-V-Tracker#38]

**Comment by SaRtORx** [comment]
LATEST CHANGES!!

PLACEHOLDER BLIP ID:437

TATTO_1_BLIP (BLIP LOCATION)
TATTO_1_CHECKPOINT_1
TATTO_1_CHECKPOINT_2

TO 

TATTO_4_BLIP
TATTO_4_CHECKPOINT_1
TATTO_4_CHECKPOINT_2

**Comment by robertnitu02** [comment]
roho interface

![Image](https://user-images.githubusercontent.com/41759393/233195817-006a8122-1e66-42c1-985c-95237b604348.png)
