### ISSUE TITLE
[Game UX] - General System Changes

### ISSUE THREAD

**Issue by SaRtORx** [B-Zone-GTA-V/B-Zone-GTA-V-Tracker#382]
Low priority - to be done before BETA

• Add 15 random questions for the Role Play test instead of 3 (from the entire bucket) - NOT MANDATORY FOR BETA!
• Increase custom vehicles cost to 12.000$ instead of 1$ (as the players will buy a car and will just drive around the map without testing all the server features)
• Enable Thirst & Hunger system 

17 April 2023

We would like to give enough money for the user to purchase Asbo / Blista. (1000$ IN BANK -  money granted at the beginning of his account - (asbo 500$ / blista 750$)

In this scenario we should increase the stock for Asbo / Blista to 5000 (if possible)

•Rewrite the FTUE message to

EN: Congratulations! You have received $1000 to purchase a vehicle (press L-GPS for details)!
RO:Felicitari! Ai primit 1000$ pentru a iti achizitiona un vehicul (apasa L-GPS pentru detalii)!

• Close Casino in Open Beta

**Comment by robertnitu02** [comment]
* +Remove HELP interface and replace with Wiki
