### ISSUE TITLE
[Gun Shop] - Gun Shop adjustments

### ISSUE THREAD

**Issue by SaRtORx** [B-Zone-GTA-V/B-Zone-GTA-V-Tracker#408]
• price adjustments

baseabll bat 8500
knucles 8500
knife - 13.000
bottle - 12.000
machete - 10.000$ 
switchblade -  15.000$
dagger - 14.000$

• Add new actionable doors to the Gun Shop

saved pos:
gunshop_doors_1 to gunshop_doors_5

Please make that those doors can be used (opened/closed) only by Admin Level 5 and above.

**Comment by robertnitu02** [comment]
+ Modify weapons camera shake
