### ISSUE TITLE
[Improvements] - Release day improvements

### ISSUE THREAD

**Issue by andreirosu97** [B-Zone-GTA-V/B-Zone-GTA-V-Tracker#652]
- [x] sa poti pescui si cu o tasta (tinand apasat) nu doar cu click + afisata in sfaturi
- [x] adaugat 1 pompa de unde sa alimentezi canistra / autospeciala la mecanici
- [x] de adaugat un shop 24/7 in incinta spitalului pillbox (la etajul 1) & in al 2-lea spital (ala secundar din ls)
- [x] de adaugat garajul de la Spital Pillbox 2
- [x] de adaugat comanda /reload ce sa dea reload la microfon automat
- [x] sa poti sa folosesti HOME cand esti mort sa vezi ID jucator in caz de RDM/VDM
- [x] de blocat somehow telefonul cat timp jucatorul este in inchisoare
- [x] improve electrician 4+ payout (ivestigate with new analytics)
- [x] scuter la remat -> adaugat in savepos uri
- [x] rename PARAMEDIC HELI NPC into Captain Mondo 
- [ ] de remove ceva pilon de la Pill box (check discord)
- [x] scoase usile 114 & 116
- [x] de adaugat update la job paycheck & faction duty at resource stop
- [x] don't check for flyhack when carried
- [x] mesaj informativ + grayed out buttons la craftman
- [x] lock-unlock la motoare

**Comment by robertnitu02** [comment]
Testing all features: https://www.youtube.com/watch?v=0D-BWFdxK7g
